# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # Back
    directory: "/master-ugr.calculator.back-end/"
    schedule:
      interval: "weekly"
    target-branch: "back-end"

  - package-ecosystem: "nuget" # Front
    directory: "/master-ugr.calculator.front-end/"
    schedule:
      interval: "weekly"
    target-branch: "front-end"

  - package-ecosystem: "nuget" # Lib
    directory: "/master-ugr.calculator.lib/"
    schedule:
      interval: "weekly"
    target-branch: "lib"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
